name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions
      with:
        github_access_token: ${{ secrets.TOKEN }}
        build_configuration: staging # The build environment for the app. please look configurations in your angular.json
        base_href: /drewwaller0015.github.io/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: gh-pages # The branch the action should deploy to.
        build_folder: dist/my-app # The folder where your project is supposed to be after running ng build by the action.
